### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hedleysmith** [allenheltondev/postman-contract-test-generator#1]
Great work on the project!

I've been trying to get it up and running, but I'm encountering the following error (as logged in the Postman runner console):
    
`TypeError: Cannot read property 'length' of undefined`

This is at the point of running the `Contract Tests / Test Request` endpoint. I've got a feeling it could be the line `for(let i = 0; i < schemaTest.parameters.length; i++){` causing the error as when I inspect the collection variable `coll-schemaTests` there appears to be no parameters in each of the tests.

e.g here is an example of one of the tests:

```

  {
    "path": "https://example.io/api/v3/suppliers/{supplierId}",
    "method": "GET",
    "responses": [
      {
        "statusCode": 200,
        "$ref": "#/components/schemas/EnergySupplier"
      },
      {
        "statusCode": null,
        "$ref": "#/components/schemas/Error"
      }
    ],
    "name": "GET - /suppliers/{supplierId} - No Request Body - SUCCESS: true",
    "success": true
  }
```

**Comment by allenheltondev** [comment]
Do you know if this is running in the prerequest script or if this error is happening in the test scripts?

Would you be willing to share your OAS?

I see you have a `statusCode` of null in there, that makes me think the format might not be right.

**Comment by esther-lyondelsordo** [comment]
This issue would be solved by this PR: https://github.com/allenheltondev/postman-contract-test-generator/pull/5

**Comment by allenheltondev** [comment]
Merged PR that resolves the issue.
