### ISSUE TITLE
Get API Schema request does not pass test.

### ISSUE THREAD

**Issue by Jankoekenpan** [allenheltondev/postman-contract-test-generator#18]
Using the [Pet Store](https://github.com/swagger-api/swagger-petstore) example of OpenAPI, the 'Get API Schema' request does not pass the test. The test script for this request expects that the responded `jsonData` contains a property `schema`, but this property is absent from the `jsonData` object. How should this property be populated? Is there anything I'm missing? Is my understanding correct that getting the schema is a mandatory step before executing the Test Request? 

Screenshot:
![image](https://github.com/allenheltondev/postman-contract-test-generator/assets/27810652/80765e32-be90-4255-b00f-5ae5d96750b2)

**Comment by allenheltondev** [comment]
What values do you have configured for the path parameters? I see in the console it worked at least once then failed when hitting your implementation of the pet store API.

Happy to help further if you're still having issues.
