### ISSUE TITLE
schemaParam is not defined

### ISSUE THREAD

**Issue by iTiamo** [allenheltondev/postman-contract-test-generator#3]
Another issue is raised in the testing of requests for non-reference parameters, in the pre-request script for "Test Request".

https://github.com/allenheltondev/postman-contract-test-generator/blob/da0f19e125f5617cf264af8710739811a2803ce7/src/Contract%20Test%20Generator.postman_collection.json#L1038

`schemaParam` is not defined here and should be changed to `param`

**Comment by esther-lyondelsordo** [comment]
This would be solved by this PR: https://github.com/allenheltondev/postman-contract-test-generator/pull/5

**Comment by allenheltondev** [comment]
Merged PR that resolves this issue. thank you @warrenty898
