### ISSUE TITLE
SchemaTest definition doesn't define primitive paramaters properly

### ISSUE THREAD

**Issue by iTiamo** [allenheltondev/postman-contract-test-generator#4]
In the pre-request script for "Build Schema Tests", parameters get defined in the following line:

https://github.com/allenheltondev/postman-contract-test-generator/blob/da0f19e125f5617cf264af8710739811a2803ce7/src/Contract%20Test%20Generator.postman_collection.json#L697

this doesn't work for my OAS document as it has the structure `schema.paths.method.parameters`, leading to parameters being `undefined`.

Adding a line such as `currentPath.parameters = pathMethod.parameters;` in the for loop fixes this issue.

**Comment by twosdai** [comment]
Had the same issue, just wanted to say thanks and for calling this out. I can make a PR for this soon if you can't @allenheltondev  or @iTiamo

**Comment by allenheltondev** [comment]
This has been fixed in a push today. Thank you both for your input on this
